version: '3'
services:
  stockapp:
    build: .
    environment:
      SPRING_DATASOURCE_USERNAME: stockAppUser
      SPRING_DATASOURCE_PASSWORD: changeit
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/stock_app?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&allowPublicKeyRetrieval=true
    ports:
      - "8080:8080"
    depends_on:
      - database
      - rabbitmq
  database:
    container_name: mysql
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: stock_app
      MYSQL_USER: stockAppUser
      MYSQL_PASSWORD: changeit
      MYSQL_ROOT_PASSWORD: changeit
    ports:
      - "3306:3306"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"