services:
  stockapp:
    container_name: stock-exchange-app
    image: s1gawron/stock-exchange-app:1.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
      FINNHUB_TOKEN: #Paste free finnhub token here
    ports:
      - "8080:8080"
    depends_on:
      - database
      - rabbitmq
  database:
    container_name: mysql
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: stock_app
      MYSQL_USER: stockAppUser
      MYSQL_PASSWORD: changeit
      MYSQL_ROOT_PASSWORD: changeit
    ports:
      - "3306:3306"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
