apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-app-configmap
data:
  database-url: jdbc:mysql://mysql-service:3306/stock_app?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&allowPublicKeyRetrieval=true